# Generated by Django 4.1.7 on 2023-03-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_price_to_unitPrice'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='-'),
            preserve_default=False,
        ),
    ]
